# Generated by Django 3.1.1 on 2020-10-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoulder_compare', models.DecimalField(decimal_places=3, max_digits=6)),
                ('chest_compare', models.DecimalField(decimal_places=3, max_digits=6)),
                ('arm_compare', models.DecimalField(decimal_places=3, max_digits=6)),
                ('total_length_compare', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoulder_result', models.DecimalField(decimal_places=3, max_digits=6)),
                ('chest_result', models.DecimalField(decimal_places=3, max_digits=6)),
                ('arm_result', models.DecimalField(decimal_places=3, max_digits=6)),
                ('total_length_result', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
