# Generated by Django 3.1.1 on 2020-10-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newcloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(max_length=255)),
                ('shoulder', models.DecimalField(decimal_places=3, max_digits=6)),
                ('chest', models.DecimalField(decimal_places=3, max_digits=6)),
                ('arm', models.DecimalField(decimal_places=3, max_digits=6)),
                ('total_length', models.DecimalField(decimal_places=3, max_digits=6)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
