# Generated by Django 3.1.1 on 2020-10-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcloth',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
