# Generated by Django 3.1.1 on 2020-10-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closets', '0002_auto_20201011_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcloth',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
