# Generated by Django 3.1.1 on 2020-10-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closets', '0004_auto_20201014_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcloth',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='newcloth',
            name='review',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newcloth',
            name='shopping_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newcloth',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Photocloset',
        ),
    ]
