# Generated by Django 3.1.1 on 2020-10-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closets', '0008_newcloth_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcloth_closet',
            name='writer_c',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
