# Generated by Django 3.1.1 on 2020-10-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closets', '0009_newcloth_closet_writer_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcloth',
            name='parent_category',
            field=models.CharField(default='상위', max_length=255),
        ),
        migrations.AddField(
            model_name='newcloth',
            name='subcategory',
            field=models.CharField(default='반팔티', max_length=255),
        ),
        migrations.AddField(
            model_name='newcloth_closet',
            name='parent_category_c',
            field=models.CharField(default='상위', max_length=255),
        ),
        migrations.AddField(
            model_name='newcloth_closet',
            name='subcategory_c',
            field=models.CharField(default='반팔티', max_length=255),
        ),
    ]
