# Generated by Django 3.1.1 on 2020-10-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closets', '0010_auto_20201025_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcloth',
            name='parent_category',
            field=models.CharField(default='상의', max_length=255),
        ),
        migrations.AlterField(
            model_name='newcloth_closet',
            name='parent_category_c',
            field=models.CharField(default='상의', max_length=255),
        ),
    ]
