# Generated by Django 3.1.1 on 2020-10-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measureguides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='image',
            new_name='guide_image',
        ),
    ]
